Ticket#6722 - Agregar type Reporte y sus subtypes
sedici/DSpace pull request #113
Opened 2022-11-28 14:13 UTC by GarrafaGalactica

Agrega el tipo Reporte con sus subtipos "Infrome de proyecto" y "Reporte tecnico" y el mapeo a oai

2022-11-28 15:12 UTC, santit96 requested changes

2022-11-28 15:12 UTC, santit96 commented on Dockerfile
> +# This image will be published as dspace/dspace sdsdsdsd
Rafa, aca se paso esto en el Dockerfile

2022-11-28 15:12 UTC, santit96 commented on dspace/config/input-forms.xml
> +                <displayed-value>Reporte tecnico</displayed-value>
Acá falta el acento, pero solo en el displayed value

2022-11-28 15:14 UTC, santit96 commented on dspace/config/input-forms.xml
> +                <displayed-value>Reporte tecnico</displayed-value>
También la identación quedó medio rara

2022-11-28 15:17 UTC, santit96 commented on Dockerfile
> +# This image will be published as dspace/dspace sdsdsdsd
Esto seguro es porque se pasó un commit de "probando", no debería ir ese commit en el merge, asi que con un rebase --amend creo que se puede sacar

2022-12-02 12:58 UTC, PabloDeAlbu commented
Probé local y funciona correctamente. Mergeo y cierro el PR

2022-12-02 12:59 UTC, merged